spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projectHub
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
    show-sql: true
