spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?sslmode=require
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
