spring:
  data:
    mongodb:
      uri: mongodb+srv://projectHub-backend:ZOMB4NEbjG640xrF@cluster0.fku4y.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

  mail:
    host: smtp.gmail.com
    port: 587
    username: avinashvijayvargiya324@gmail.com
    password: ${PASSWORD}

    # Other properties
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

          # TLS , port 587
          starttls:
            enable: true