spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projectHub
    username: postgres
    password: root
    #maximum pool size #https://stackoverflow.com/a/68270053
    hikari.max-pool-size: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
    show-sql: true
